/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kyUrgzkUvVbdwgr9F8D7qC
import { createUseStyleTokens } from "@plasmicapp/react-web";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: kyUrgzkUvVbdwgr9F8D7qC/projectModule
import projectcss from "./plasmic.module.css"; // plasmic-import: kyUrgzkUvVbdwgr9F8D7qC/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
